// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flake_API.Services;

#nullable disable

namespace flakeAPI.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("flake_API.Models.LocationModel", b =>
            {
                b.Property<string>("State")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("State");

                b.ToTable("Location");

                b.HasData(
                    new
                    {
                        State = "dhaka"
                    },
                    new
                    {
                        State = "sylhet"
                    },
                    new
                    {
                        State = "mymensingh"
                    },
                    new
                    {
                        State = "rajshahi"
                    },
                    new
                    {
                        State = "dinajpur"
                    },
                    new
                    {
                        State = "rangpur"
                    },
                    new
                    {
                        State = "barisal"
                    },
                    new
                    {
                        State = "chittagong"
                    });
            });

        modelBuilder.Entity("flake_API.Models.WeatherDataModel", b =>
            {
                b.Property<DateTime>("Time")
                    .HasColumnType("datetime2");

                b.Property<double>("Humidity")
                    .HasColumnType("float");

                b.Property<double>("Latitude")
                    .HasColumnType("float");

                b.Property<string>("LocationState")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<double>("Longitude")
                    .HasColumnType("float");

                b.Property<double>("Pressure")
                    .HasColumnType("float");

                b.Property<double>("Temperature")
                    .HasColumnType("float");

                b.HasKey("Time");

                b.HasIndex("LocationState");

                b.ToTable("Weather");
            });

        modelBuilder.Entity("flake_API.Models.WeatherDataModel", b =>
            {
                b.HasOne("flake_API.Models.LocationModel", "Location")
                    .WithMany()
                    .HasForeignKey("LocationState")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Location");
            });
#pragma warning restore 612, 618
    }
}
